version: '3.8'

services:
  frontend:
    image: httpd:latest
    container_name: nikolapp-frontend
#    ports:
#      - "9007:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    networks:
      - nikolapp-network
      - reverse-proxy-network


  backend:
    image: python:3.9
    container_name: nikolapp-backend
    ports:
      - "9008:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
  command: sh -c "pip install -r requirements.txt && python app.py"
    networks:
      - nikolapp-network
      - reverse-proxy-network


networks:
  nikolapp-network:
    driver: bridge  # Réseau interne propre à ce projet
  reverse-proxy-network:
    external: true  # Réseau partagé avec le reverse proxy
